# Generated by Django 5.0.2 on 2024-09-22 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0003_crawlingresult_delete_searchresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingresult',
            name='backlinks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='canonical_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='dofollow_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='external_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='internal_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='nofollow_links',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='crawlingresult',
            name='non_canonical_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name='crawlingresult',
            unique_together={('user', 'url')},
        ),
    ]
