# Generated by Django 5.0.2 on 2024-09-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_crawlingresult_backlinks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlingresult',
            name='backlinks_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='broken_images_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='broken_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='canonical_urls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='crawled_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='dofollow_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='external_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='h1_info_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='html_pages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='image_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='indexed_urls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='internal_links',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='internal_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='meta_description_info_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='nofollow_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='non_canonical_urls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='non_html_files_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='non_indexed_urls_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='title_info_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='uncrawled_links_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawlingresult',
            name='word_count_info_count',
            field=models.IntegerField(default=0),
        ),
    ]
